Repository Horde-Of-Greg/HOGifactory, pull requests merged in 2024-11, with the labels that each got.

#1 Change the Issues Templates
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/ISSUE_TEMPLATE/002-feature-request.yml
Labels: help wanted

#5 Add ZBGT
  manifest.json
Labels: enhancement

#3 Readme update
  README.md
  assets/images/HOGifactory-logo.png
Labels: documentation, help wanted

#6 General cleanup
  .github/workflows/createchangelog.yml
  .github/workflows/deploygh.yml
  .github/workflows/forkprbuildpack.yml
  .github/workflows/releasecommit.yml
  .github/workflows/testbuildpack.yml
  .github/workflows/testcommits.yml
  .github/workflows/updateEnglishLang.yml
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config/CustomMainMenu/mainmenu.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/config/craftpresence.json
  overrides/groovy/runConfig.json
  serverfiles/server-icon.png
  serverfiles/server.properties
  tools/globals.ts
  tools/tasks/changelog/definitions.ts
  tools/tasks/changelog/specialParser.ts
  tools/tasks/client/index.ts
  tools/tasks/deploy/curseforge.ts
  tools/tasks/misc/transformFiles.ts
  tools/tasks/shared/index.ts
  tools/templates/mainmenu.json
  tools/templates/versions.txt
  tools/types/transformFiles.ts
Labels: help wanted, cleanup

#14 Title screen changes and more cleanup
  .github/ISSUE_TEMPLATE/config.yml
  .gitignore
  manifest.json
  overrides/config/CustomMainMenu/mainmenu.json
  overrides/config/nomilabs.cfg
  overrides/groovy/postInit/Post-Initial/Main/Mode-Specific/Expert-Mode/rareEarth.groovy
  overrides/resources/minecraft/textures/gui/title/background/abomination.jpg
  overrides/resources/minecraft/textures/gui/title/background/audi_fusion.jpg
  overrides/resources/minecraft/textures/gui/title/background/besoiobiy_1.jpg
  overrides/resources/minecraft/textures/gui/title/background/besoiobiy_2.jpg
  overrides/resources/minecraft/textures/gui/title/background/cactus_cool.jpg
  overrides/resources/minecraft/textures/gui/title/background/cobracreeper1.jpg
  overrides/resources/minecraft/textures/gui/title/background/darkarkangel.jpg
  overrides/resources/minecraft/textures/gui/title/background/ely_1.jpg
  overrides/resources/minecraft/textures/gui/title/background/ely_2.jpg
  overrides/resources/minecraft/textures/gui/title/background/ely_3.jpg
  overrides/resources/minecraft/textures/gui/title/background/emiuna.jpg
  overrides/resources/minecraft/textures/gui/title/background/extracoolcat_1.jpg
  overrides/resources/minecraft/textures/gui/title/background/extracoolcat_2.jpg
  overrides/resources/minecraft/textures/gui/title/background/extracoolcat_3.jpg
  overrides/resources/minecraft/textures/gui/title/background/extracoolcat_4.jpg
  overrides/resources/minecraft/textures/gui/title/background/fuge_tower.jpg
  overrides/resources/minecraft/textures/gui/title/background/gaboggamer.jpg
  overrides/resources/minecraft/textures/gui/title/background/itstheguywhoasked.jpg
  overrides/resources/minecraft/textures/gui/title/background/lyeo.jpg
  overrides/resources/minecraft/textures/gui/title/background/pgs_1.jpg
  overrides/resources/minecraft/textures/gui/title/background/pgs_2.jpg
  overrides/resources/minecraft/textures/gui/title/background/qr_est.jpg
  overrides/resources/minecraft/textures/gui/title/background/steamchad.jpg
  overrides/resources/minecraft/textures/gui/title/background/supasem.jpg
  overrides/resources/minecraft/textures/gui/title/top.png
  overrides/resources/modpack/lang/en_us.lang
  overrides/resources/modpack/textures/gui/default_title.png
  overrides/resources/modpack/textures/logo/16x.png
  overrides/resources/modpack/textures/logo/256x.png
  overrides/resources/modpack/textures/logo/32x.png
  overrides/resources/pack.mcmeta
  tools/templates/mainmenu.json
Labels: enhancement, cleanup

#16 Add new logos
  assets/images/HOGifactory-logo.png
  overrides/resources/minecraft/textures/gui/title/background/abomination2.png
  overrides/resources/minecraft/textures/gui/title/top.png
  overrides/resources/modpack/textures/logo/16x.png
  overrides/resources/modpack/textures/logo/256x.png
  overrides/resources/modpack/textures/logo/32x.png
Labels: enhancement, cleanup
